Upgrade react native screens (#626)
## Description
Android only:
The current version of `react-native-screens` crashes the app when using compile sdk 35+ and using a phone with android < 35

see: 
https://stackoverflow.com/questions/79139467/react-native-android-java-lang-nosuchmethoderror-no-interface-method-removelas
and:
https://developer.android.com/about/versions/15/behavior-changes-15?hl=en#openjdk-api-changes

## Changes
Upgrade react-native-screens to 3.35.0 which is compatible with Android 35
## Checklist
- [x] 🗒 `CHANGELOG` entry

---------

Co-authored-by: saravanan <saravanan.silvarajoo@bitmovin.com>